version: "3.9"
services:
    nginx:
        image: nginx:alpine
        container_name: 'tg-bot-article-nginx'
        ports:
            - ${HOST_PORT}:${CONTAINER_PORT}
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - php-fpm

    php-fpm:
        container_name: "tg-bot-article-php-fpm"
        build:
            context: .
            dockerfile: 'docker/php-fpm/Dockerfile'
        volumes:
            - ./:/var/www/app

    php-cli:
        container_name: "tg-bot-article-php-cli"
        build:
            context: .
            dockerfile: 'docker/php-cli/Dockerfile'
        volumes:
            - ./:/var/www/app

    redis:
        container_name: 'tg-bot-redis'
        image: redis:alpine
        ports:
            - ${REDIS_HOST_PORT}:${REDIS_PORT}
        command: redis-server --loglevel warning
